[package]
edition = "2021"
name = "web-demo"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies.szalinski-egg]
path = ".."

[dependencies]
wasm-bindgen = "0.2"
egg = {version = "0.9.3", features = ["wasm-bindgen"]}